# Generated by Django 5.1.5 on 2025-03-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['id']},
        ),
    ]
