# Generated by Django 5.1.5 on 2025-05-05 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_unit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitimage',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit'),
        ),
    ]
