# Generated by Django 5.1.5 on 2025-05-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_unitimage_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='consultationtype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='unitrequest',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='unit',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='approver_message',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
