# Generated by Django 5.1.5 on 2025-05-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_article_options_alter_consultation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
