# Generated by Django 5.1.5 on 2025-06-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_unitrequest_sales_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='proposal_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
