# Generated by Django 5.1.5 on 2025-03-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
