# Generated by Django 5.1.5 on 2025-03-12 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesrequest',
            name='sales_request_unique_constraint',
        ),
        migrations.AlterField(
            model_name='salesrequest',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.unitrequest'),
        ),
    ]
