# Generated by Django 5.1.5 on 2025-05-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0002_remove_salesrequest_sales_request_unique_constraint_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesRequest',
        ),
    ]
